export const NAVIGATION_ROUTES = {
  DASHBOARD: "/dashboard",
  LOGIN: "/",
  LOGIN2: "/login",
  PROPERTIES: "/all-properties",
  ABOUT: "/about-us",
  HOME: "/home",
  SLIDERS: "sliders",
  CATEGORY: "category",
  SERVICES: "services",
  TEAMS: "teams",
  CONTACT: "/contact",
  SETTINGS: "settings",
  PROPERTY_DETAILS: "/property-details",
  ADMIN_SLIDERS: "sliders",
  ADMIN_CATEGORY: "category",
  ADMIN_SERVICES: "services",
  ADMIN_TEAMS: "teams",
  ADMIN_SETTINGS: "settings",
  ADMIN_PROPERTIES: "properties",
  ADMIN_TESTIMONIALS: "testimonials",
};
